[package]
name = "toolchain_find"
version = "0.1.2"
authors = ["Garrett Squire <garrettsquire@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/gsquire/toolchain_find"
documentation = "https://docs.rs/toolchain_find"
description = "A small library to help find installed Rust components"
readme = "README.md"

[dependencies]
dirs = "1.0"
semver = "0.9"
walkdir = "2.2"
